<?php

namespace Database\Seeders;

use App\Models\Doctor;
use Illuminate\Database\Seeder;

class DoctorSeeder extends Seeder
{
    public function run()
    {
        $doctorsData = [
            'Dr. Nourhan Ali' => ['ar' => "استشاري أول جراحات التجميل والليزر، خبرة تزيد عن 20 عاماً في نحت القوام وتنسيق الجسم. حاصلة على البورد الأمريكي في التجميل الجراحي وغير الجراحي، وتعتبر رائدة في تقنيات شد الوجه بالخيوط الحديثة. تهدف د. نورهان دائماً إلى دمج الفن بالطب لتحقيق نتائج طبيعية تعزز من ثقة المرضى بأنفسهم.", 'en' => "Senior Consultant of Plastic Surgery and Laser, with over 20 years of experience in body contouring and sculpting. American Board-certified in surgical and non-surgical aesthetics, she is a pioneer in modern thread lift techniques. Dr. Nourhan always aims to blend art with medicine to achieve natural results that boost patients' self-confidence."],
            'Dr. Sarah Adel' => ['ar' => "أخصائي الأمراض الجلدية والتجميل، متخصصة في علاج مشاكل البشرة المعقدة مثل حب الشباب والندبات. تستخدم أحدث أجهزة الليزر لعلاج التصبغات وتجديد خلايا البشرة. تتميز د. سارة بوضع برامج علاجية مخصصة لكل مريض بناءً على نوع بشرته واحتياجاتها الفردية لضمان الحصول على بشرة صحية ومشرقة.", 'en' => "Dermatology and Aesthetics Specialist, specializing in treating complex skin issues such as acne and scarring. She utilizes the latest laser technology for pigment treatment and skin rejuvenation. Dr. Sarah is distinguished by creating customized treatment programs for each patient based on their individual skin type and needs to ensure healthy, glowing skin."],
            'Dr. Mahmoud Kamal' => ['ar' => "خبير تجميل متخصص في حقن الفيلر والبوتكس وتجديد نضارة الوجه. له باع طويل في تصميم الابتسامة وتجميل ملامح الوجه بطريقة متناغمة. يهتم د. محمود بأدق التفاصيل التشريحية للوجه لضمان الحصول على نتائج تبدو طبيعية تماماً بعيداً عن المبالغة، مع التركيز على السلامة المهنية العالية.", 'en' => "Cosmetic expert specializing in fillers, Botox injections, and facial rejuvenation. He has extensive experience in smile design and harmonizing facial features. Dr. Mahmoud pays close attention to the finest anatomical details of the face to ensure completely natural-looking results, with a high focus on professional safety."],
            'Dr. Reem Khaled' => ['ar' => "أخصائي تجميل ومكافحة الشيخوخة. تركز د. ريم على العلاجات غير الجراحية لشد الجلد وتحفيز الكولاجين. تسعى دائماً لمتابعة كل جديد في عالم التجميل عالمياً لتطبيقه في عيادتها. تُعرف بمهارتها العالية في التعامل مع الحالات التي تتطلب دقة متناهية في رسم ملامح الوجه.", 'en' => "Aesthetics and anti-aging specialist. Dr. Reem focuses on non-surgical skin tightening and collagen stimulation treatments. She constantly seeks to follow every new development in the global aesthetic world to implement in her clinic. She is known for her high skill in handling cases that require extreme precision in shaping facial features."],
            'Dr. Heba Mahmoud' => ['ar' => "أخصائي تغذية علاجية معتمدة، متخصصة في وضع خطط غذائية للحالات المزمنة مثل السكري والضغط. تؤمن بأن الغذاء هو الدواء الأول، وتعمل مع مرضاها على تغيير أنماط حياتهم بشكل جذري ومستدام بدلاً من الأنظمة القاسية التي تضر أكثر مما تنفع.", 'en' => "Certified Clinical Nutritionist, specializing in developing dietary plans for chronic conditions such as diabetes and hypertension. She believes that food is the primary medicine and works with her patients to radically and sustainably change their lifestyles, rather than resorting to harsh diets that do more harm than good."],
            'Dr. Mona Salem' => ['ar' => "خبير تغذية علاجية، تهتم بتغذية الرياضيين والأنظمة الغذائية للنباتيين. حاصلة على ماجستير في علوم التغذية وتقدم استشارات دقيقة حول المكملات الغذائية وسلامة الأغذية. تهدف د. منى إلى تعليم مرضاها كيفية الاستماع لأجسادهم واختيار الأطعمة التي تمنحهم الطاقة والحيوية.", 'en' => "Clinical Nutritionist, focused on sports nutrition and vegan diets. She holds a Master's degree in Nutritional Sciences and provides precise consultations on dietary supplements and food safety. Dr. Mona aims to teach her patients how to listen to their bodies and choose foods that give them energy and vitality."],
            'Dr. Tarek Youssef' => ['ar' => "استشاري سمنة ونحافة، متخصص في جراحات السمنة والتحويل الغذائي. يمتلك رؤية طبية شاملة لمساعدة المرضى على التخلص من الوزن الزائد بطريقة آمنة. يهتم د. طارق بالمتابعة الدورية بعد العمليات لضمان عدم استعادة الوزن والحفاظ على صحة المريض العامة.", 'en' => "Obesity and weight loss consultant, specializing in bariatric surgery and metabolic transitions. He possesses a comprehensive medical vision to help patients lose excess weight safely. Dr. Tarek focuses on regular post-operative follow-ups to ensure weight maintenance and overall patient health."],
            'Dr. Nadia Hassan' => ['ar' => "مستشار تغذية متخصصة في صحة الأطفال والنمو. تقدم استشارات غذائية دقيقة تعتمد على أحدث الدراسات العلمية لضمان نمو صحي للأطفال. د. نادية معروفة بقدرتها على التعامل مع حالات الحساسية الغذائية ووضع خطط تناسب طبيعة حياة كل عائلة.", 'en' => "Nutrition consultant specializing in child health and growth. She provides precise nutritional consultations based on the latest scientific studies to ensure healthy child development. Dr. Nadia is known for her ability to handle food allergy cases and create plans that fit each family's lifestyle."],
            'Dr. Mona Adel' => ['ar' => "استشاري نساء وتوليد، لديها خبرة واسعة في متابعة الحمل عالي الخطورة. تهتم د. منى بتوفير بيئة مريحة للمريضات واستخدام تقنيات السونار رباعي الأبعاد لمتابعة الجنين بدقة. تهدف دائماً إلى ضمان سلامة الأم والجنين خلال فترة الحمل والولادة.", 'en' => "OB/GYN consultant with extensive experience in high-risk pregnancy monitoring. Dr. Mona focuses on providing a comfortable environment for patients and using 4D ultrasound technology to monitor the fetus accurately. She always aims to ensure the safety of both mother and baby throughout pregnancy and childbirth."],
            'Dr. Laila Youssef' => ['ar' => "أخصائي توليد ومتابعة حمل. تتميز د. ليلى بالصبر والقدرة على تقديم الدعم النفسي والطبي للمرأة خلال مراحل الحمل المختلفة. تسعى لتقديم تجربة ولادة آمنة وإيجابية لكل أم، مع التركيز على التعليم الصحي للمرأة حول التغذية والعناية بالذات.", 'en' => "Obstetrician and pregnancy monitoring specialist. Dr. Laila is known for her patience and ability to provide emotional and medical support to women throughout various pregnancy stages. She strives to offer a safe and positive childbirth experience for every mother, focusing on educating women about nutrition and self-care."],
            'Dr. Noha Ibrahim' => ['ar' => "استشاري عقم ومساعدة على الإنجاب. خبيرة في تقنيات الحقن المجهري وأطفال الأنابيب. تمتلك د. نهى سجلاً حافلاً من النجاحات في مساعدة الأزواج على تحقيق حلم الإنجاب. تهتم بالجانب النفسي والطبي معاً، وتقدم خططاً علاجية فردية تتناسب مع حالة كل زوجين.", 'en' => "Infertility and assisted reproductive technology consultant. Expert in ICSI and IVF techniques. Dr. Noha has a track record of success in helping couples achieve the dream of parenthood. She focuses on both psychological and medical aspects, providing individualized treatment plans suited to each couple's condition."],
            'Dr. Samar Ali' => ['ar' => "أخصائي نساء وتوليد، متخصصة في الجراحات النسائية البسيطة والمعقدة. تعتمد في عملها على أحدث البروتوكولات العالمية في تشخيص وعلاج تكيسات المبايض واضطرابات الدورة الشهرية. تتميز د. سمر بدقة التشخيص وحرصها على تقديم شرح وافٍ للمريضة عن حالتها الصحية.", 'en' => "Gynecologist, specializing in both simple and complex gynecological surgeries. She relies on the latest global protocols for diagnosing and treating ovarian cysts and menstrual disorders. Dr. Samar is distinguished by diagnostic precision and her commitment to providing a clear explanation of the patient's health condition."],
            'Dr. Ahmed Mahmoud' => ['ar' => "طبيب أسنان عام، متخصص في التركيبات وتجميل الأسنان. يمتلك د. أحمد خبرة طويلة في علاج الجذور وتجميل الابتسامة باستخدام مواد عالية الجودة. يهتم دائماً بتوفير تجربة مريحة للمريض وتقليل الشعور بالألم أثناء الإجراءات الطبية.", 'en' => "General dentist, specializing in prosthodontics and cosmetic dentistry. Dr. Ahmed has extensive experience in root canal treatments and smile design using high-quality materials. He is always committed to providing a comfortable experience for the patient and minimizing pain during medical procedures."],
            'Dr. Mohamed Tarek' => ['ar' => "أخصائي تجميل أسنان وتقويم. يتميز د. محمد بمهارة عالية في تصميم الابتسامة باستخدام تقنيات ديجيتال متطورة. يسعى لتقديم نتائج جمالية دقيقة تتماشى مع تناسق الوجه، مع التركيز على الحفاظ على صحة الأسنان الطبيعية.", 'en' => "Cosmetic dentist and orthodontist. Dr. Mohamed is skilled in smile design using advanced digital techniques. He strives to provide precise aesthetic results that match facial symmetry, while focusing on maintaining natural tooth health."],
            'Dr. Alaa Saeed' => ['ar' => "جراح فم وأسنان، خبير في زراعة الأسنان والجراحات الفكية. يمتلك د. علاء مهارات جراحية استثنائية وقدرة على التعامل مع الحالات الجراحية المعقدة. يضمن دائماً توفير رعاية متكاملة قبل وبعد الجراحة لضمان سرعة الشفاء.", 'en' => "Oral surgeon, expert in dental implants and jaw surgeries. Dr. Alaa possesses exceptional surgical skills and the ability to handle complex surgical cases. He always ensures providing comprehensive care before and after surgery to guarantee quick healing."],
            'Dr. Mayada Fathy' => ['ar' => "أخصائي تقويم أسنان للبالغين والأطفال. تسعى د. ميادة دائماً لاستخدام أحدث تقنيات التقويم الشفاف والمعدني لتحسين الإطباق وتجميل الابتسامة. تتميز بوضع خطط علاجية طويلة الأمد تضمن الحفاظ على النتائج التي يصل إليها المريض.", 'en' => "Orthodontist for adults and children. Dr. Mayada always strives to use the latest clear and metal aligner techniques to improve occlusion and aesthetic smiles. She is distinguished by creating long-term treatment plans that ensure the results the patient achieves are maintained."],
            'Dr. Karim Hassan' => ['ar' => "أخصائي علاج طبيعي وتأهيل حركي. خبير في التعامل مع آلام المفاصل والعمود الفقري. يستخدم د. كريم برامج تأهيلية تعتمد على العلاج اليدوي والتمارين العلاجية المبتكرة لمساعدة المرضى على استعادة حركتهم الطبيعية في أسرع وقت.", 'en' => "Physiotherapist and movement rehabilitation specialist. Expert in dealing with joint and spine pain. Dr. Karim uses rehabilitation programs based on manual therapy and innovative therapeutic exercises to help patients regain their natural movement as quickly as possible."],
            'Dr. Omar Farouk' => ['ar' => "خبير إصابات ملاعب وتأهيل رياضي. يهتم د. عمر بمساعدة الرياضيين على التعافي من الإصابات والعودة للمنافسة بقوة. يستخدم أحدث الوسائل التكنولوجية في العلاج الطبيعي والتدريب التأهيلي لتقوية العضلات ومنع تكرار الإصابة.", 'en' => "Sports injury expert and athletic rehabilitation specialist. Dr. Omar focuses on helping athletes recover from injuries and return to competition stronger. He uses the latest technological tools in physical therapy and rehabilitation training to strengthen muscles and prevent injury recurrence."],
            'Dr. Yasmin Kamal' => ['ar' => "أخصائي تأهيل حركي وعصبي. تهتم د. ياسمين بمرضى الشلل الدماغي وإصابات الجهاز العصبي. تمتلك خبرة واسعة في تصميم برامج تأهيلية مخصصة تساعد على تحسين جودة الحياة والاستقلالية الحركية للمرضى.", 'en' => "Movement and neurological rehabilitation specialist. Dr. Yasmin focuses on patients with cerebral palsy and nervous system injuries. She possesses extensive experience in designing customized rehabilitation programs that help improve the quality of life and motor independence for patients."],
            'Dr. Hany Mamdouh' => ['ar' => "أخصائي عمود فقري وتأهيل قوام. يركز د. هاني على علاج حالات الانزلاق الغضروفي والانحرافات العمودية بدون جراحة. يستخدم تقنيات متطورة في العلاج الطبيعي لتخفيف الضغط على الأعصاب واستعادة القوام السليم.", 'en' => "Spine specialist and posture rehabilitation. Dr. Hany focuses on treating herniated disc cases and spinal curvatures without surgery. He uses advanced techniques in physical therapy to relieve pressure on nerves and restore proper posture."],
            'Dr. Mostafa Kamal' => ['ar' => "استشاري نفسي، خبير في علاج الاضطرابات النفسية والاكتئاب والقلق. يهتم د. مصطفى بخلق مساحة آمنة للمرضى للتعبير عن مشاعرهم وفهم أسباب اضطراباتهم. يستخدم منهجية علمية حديثة في العلاج النفسي لضمان استقرار الحالة النفسية للمريض.", 'en' => "Psychiatrist, expert in treating psychological disorders, depression, and anxiety. Dr. Mostafa focuses on creating a safe space for patients to express their feelings and understand the causes of their disorders. He uses modern scientific methodology in psychotherapy to ensure the patient's psychological stability."],
            'Dr. Khaled Ibrahim' => ['ar' => "معالج سلوكي متخصص في تعديل السلوك وعلاج الوسواس القهري. يعمل د. خالد مع المرضى على كسر الأنماط الفكرية السلبية وبناء عادات صحية جديدة. يتميز بالهدوء والقدرة العالية على التحليل النفسي الدقيق.", 'en' => "Behavioral therapist specializing in behavior modification and OCD treatment. Dr. Khaled works with patients to break negative thought patterns and build new healthy habits. He is distinguished by calmness and a high ability for precise psychological analysis."],
            'Dr. Iman Abdullah' => ['ar' => "أخصائي نفسي، تركز على الصحة النفسية للمرأة والطفل. تمتلك د. إيمان مهارات عالية في التعامل مع اضطرابات ما بعد الصدمة وصعوبات التعلم. تهتم بتقديم حلول عملية للمشكلات النفسية اليومية التي تؤثر على جودة حياة الفرد.", 'en' => "Psychologist, focusing on women's and children's mental health. Dr. Iman possesses high skills in dealing with PTSD and learning difficulties. She focuses on providing practical solutions for daily psychological problems that affect an individual's quality of life."],
            'Dr. Youssef Rashad' => ['ar' => "مستشار أسري ونفسي. خبير في حل النزاعات الزوجية وتطوير مهارات التواصل داخل الأسرة. يهتم د. يوسف بتقديم استشارات متوازنة تساعد على بناء بيئة أسرية صحية ومستقرة، مع التركيز على فهم سيكولوجية العلاقات الإنسانية.", 'en' => "Family and psychological consultant. Expert in resolving marital conflicts and developing communication skills within the family. Dr. Youssef focuses on providing balanced consultations that help build a healthy and stable family environment, with a focus on understanding the psychology of human relationships."]
        ];

        foreach ($doctorsData as $nameEn => $bio) {
            // البحث عن الطبيب بالاسم وتحديث حقل bio فقط
            Doctor::whereRaw("JSON_UNQUOTE(JSON_EXTRACT(name, '$.en')) = ?", [$nameEn])
                  ->update(['bio' => $bio]);
        }
    }
}